# Generated by Django 4.1.2 on 2022-10-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_bname', models.CharField(blank=True, max_length=50)),
                ('c_sname', models.CharField(max_length=20)),
                ('c_fname', models.CharField(max_length=20)),
                ('c_email', models.CharField(max_length=30)),
                ('c_pnumber', models.CharField(max_length=20)),
                ('c_message', models.TextField(blank=True, max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_bname', models.CharField(blank=True, max_length=50)),
                ('r_sname', models.CharField(max_length=20)),
                ('r_fname', models.CharField(max_length=20)),
                ('r_message', models.TextField(blank=True, max_length=200)),
                ('rating', models.IntegerField(default=1)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
